[package]
name = "helper_macros"
version = "0.1.0"
authors = ["Shridhar Sundarraj <shridharsundarraj3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
